// dist/injector.js

/**
 * SEO DOM Injector v1.0
 * This is the final, combined script that is hosted and loaded by the client's website.
 * It contains both the configuration and the core logic in a single IIFE to prevent scope conflicts.
 * DO NOT EDIT THIS FILE DIRECTLY. Edit files in /src/ and rebuild.
 */
(function () {
    'use strict';

    // --- Part 1: The Configuration (from src/config.js) ---

    /**
     * The "Database" for the SEO Injector.
     * This object maps URL pathnames to their desired SEO metadata.
     */
    const rules = {
        "/products/example-shoe": {
            "title": "The Best Example Shoe | Awesome Brand",
            "description": "Discover the amazing comfort and style of our Example Shoe. Perfect for all occasions and built to last."
        },
        "/pages/contact": {
            "title": "Contact Us | Awesome Brand",
            "description": "Get in touch with the Awesome Brand team. We're here to help with any questions you may have."
        },
        "/": {
            "title": "Awesome Brand | The Official Homepage",
            "description": "Welcome to Awesome Brand, your number one source for high-quality products. We're dedicated to giving you the very best."
        }
    };


    // --- Part 2: The Core Logic (from src/core.js) ---

    /**
     * Applies the provided SEO data to the document's head.
     * @param {object} data - An object with 'title' and 'description' properties.
     */
    function applySEO(data) {
        // 1. Update the document title
        if (data.title) {
            document.title = data.title;
        }

        // 2. Update the meta description
        if (data.description) {
            let metaDescriptionTag = document.querySelector('meta[name="description"]');

            // If the meta description tag doesn't exist, create it.
            if (!metaDescriptionTag) {
                metaDescriptionTag = document.createElement('meta');
                metaDescriptionTag.setAttribute('name', 'description');
                // Append to the head, which is a safe fallback.
                document.head.appendChild(metaDescriptionTag);
            }

            // Set the content of the existing or newly created tag.
            metaDescriptionTag.setAttribute('content', data.description);
        }
    }

    // --- Main Execution Logic ---

    // 1. Get the current URL path.
    // We use pathname to ignore domain and query parameters.
    const currentPath = window.location.pathname;

    // 2. Check if a rule exists for the current path in the `rules` object.
    if (rules && rules[currentPath]) {
        const ruleForPath = rules[currentPath];

        // 3. Apply the SEO data from the matched rule.
        // We wait for DOMContentLoaded to ensure the <head> is available,
        // though this is a very safe operation even if run early.
        if (document.readyState === 'loading') {
            document.addEventListener('DOMContentLoaded', function () {
                applySEO(ruleForPath);
            });
        } else {
            // The DOM is already ready.
            applySEO(ruleForPath);
        }
    }


})();
